#!/usr/bin/env ruby

require 'goliath/runner'
require './garufa_app'

runner = Goliath::Runner.new(ARGV, GarufaApp.new)
runner.app = Goliath::Rack::Builder.build(GarufaApp, runner.api)

runner.log_file ||= './garufa.log'
runner.pid_file ||= './garufa.pid'

runner.run
